import glob
import numpy as np
from toolbox import Evaluations as eva

def cross_validate(storename, evalfiles):
	#storename = "DensecropNet_Iterative_gr14_agp"
	#evalfiles = ["DensecropNet_Iterative_gr14_agp_fold1_epoch250_retrieval.npy",
	#	      "DensecropNet_Iterative_gr14_agp_fold2_epoch485_retrieval.npy"]
	evaluations = []
	for eval in evalfiles:
		evaluations.append(np.load(eval))
	evaluations = np.concatenate(evaluations, axis=1)
	eva.binclass_evaluation(evaluations[1], evaluations[0], storename)

evals_basenet18lidc = ["experiments/experiments_cl/BasicNet_lidc_classification_6_fold1_epoch1306_val/BasicNet_lidc_classification_6_fold1_epoch1306_retrieval.npy",
		     "experiments/experiments_cl/BasicNet_lidc_classification_6_fold2_epoch680_val/BasicNet_lidc_classification_6_fold2_epoch680_retrieval.npy",
		     "experiments/experiments_cl/BasicNet_lidc_classification_6_fold3_epoch1202_val/BasicNet_lidc_classification_6_fold3_epoch1202_retrieval.npy",
		     "experiments/experiments_cl/BasicNet_lidc_classification_6_fold4_epoch595_val/BasicNet_lidc_classification_6_fold4_epoch595_retrieval.npy",
		     "experiments/experiments_cl/BasicNet_lidc_classification_6_fold5_epoch603_val/BasicNet_lidc_classification_6_fold5_epoch603_retrieval.npy"]
evals_basenet20lidc = ["experiments/experiments_cl/BasicNet_lidc_classification_9_fold1_epoch511_val/BasicNet_lidc_classification_9_fold1_epoch511_retrieval.npy",
		     "experiments/experiments_cl/BasicNet_lidc_classification_9_fold2_epoch735_val/BasicNet_lidc_classification_9_fold2_epoch735_retrieval.npy",
		     "experiments/experiments_cl/BasicNet_lidc_classification_9_fold3_epoch1441_val/BasicNet_lidc_classification_9_fold3_epoch1441_retrieval.npy",
		     "experiments/experiments_cl/BasicNet_lidc_classification_9_fold4_epoch542_val/BasicNet_lidc_classification_9_fold4_epoch542_retrieval.npy",
		     "experiments/experiments_cl/BasicNet_lidc_classification_9_fold5_epoch1380_val/BasicNet_lidc_classification_9_fold5_epoch1380_retrieval.npy"]
evals_basenet20sph = ["experiments/experiments_cl/BasicNet_sph_classification_8_fold1_epoch151_val/BasicNet_sph_classification_8_fold1_epoch151_retrieval.npy",
			 "experiments/experiments_cl/BasicNet_sph_classification_8_fold2_epoch563_val/BasicNet_sph_classification_8_fold2_epoch563_retrieval.npy",
			 "experiments/experiments_cl/BasicNet_sph_classification_8_fold3_epoch335_val/BasicNet_sph_classification_8_fold3_epoch335_retrieval.npy",
			 "experiments/experiments_cl/BasicNet_sph_classification_8_fold4_epoch892_val/BasicNet_sph_classification_8_fold4_epoch892_retrieval.npy",
			 "experiments/experiments_cl/BasicNet_sph_classification_8_fold5_epoch1152_val/BasicNet_sph_classification_8_fold5_epoch1152_retrieval.npy"]
evals_basenettranslidc = ["experiments/experiments_cl/BasicNet_classification_lidc_transfer_rfold1_epoch390_val/BasicNet_classification_lidc_transfer_rfold1_epoch390_retrieval.npy",
			"experiments/experiments_cl/BasicNet_classification_lidc_transfer_rfold2_epoch1360_val/BasicNet_classification_lidc_transfer_rfold2_epoch1360_retrieval.npy",
			"experiments/experiments_cl/BasicNet_classification_lidc_transfer_rfold3_epoch1310_val/BasicNet_classification_lidc_transfer_rfold3_epoch1310_retrieval.npy",
			"experiments/experiments_cl/BasicNet_classification_lidc_transfer_rfold4_epoch1380_val/BasicNet_classification_lidc_transfer_rfold4_epoch1380_retrieval.npy",
			"experiments/experiments_cl/BasicNet_classification_lidc_transfer_rfold5_epoch1330_val/BasicNet_classification_lidc_transfer_rfold5_epoch1330_retrieval.npy"]
evals_basenettranssph = ["experiments/experiments_cl/BasicNet_classification_sph_transfer_rfold1_epoch1020_val/BasicNet_classification_sph_transfer_rfold1_epoch1020_retrieval.npy",
			 "experiments/experiments_cl/BasicNet_classification_sph_transfer_rfold2_epoch1190_val/BasicNet_classification_sph_transfer_rfold2_epoch1190_retrieval.npy",
			 "experiments/experiments_cl/BasicNet_classification_sph_transfer_rfold3_epoch300_val/BasicNet_classification_sph_transfer_rfold3_epoch300_retrieval.npy",
			 "experiments/experiments_cl/BasicNet_classification_sph_transfer_rfold4_epoch50_val/BasicNet_classification_sph_transfer_rfold4_epoch50_retrieval.npy",
			 "experiments/experiments_cl/BasicNet_classification_sph_transfer_rfold5_epoch71_val/BasicNet_classification_sph_transfer_rfold5_epoch71_retrieval.npy"]
evals_dfcnlidcr = ["experiments/experiments_cl/ParamDenseCropNet_classification_lidc_rfold1%7C10_epoch261_val/ParamDenseCropNet_classification_lidc_rfold1%7C10_epoch261_retrieval.npy",
			"experiments/experiments_cl/ParamDenseCropNet_classification_lidc_rfold2%7C10_epoch350_val/ParamDenseCropNet_classification_lidc_rfold2%7C10_epoch350_retrieval.npy",
			"experiments/experiments_cl/ParamDenseCropNet_classification_lidc_rfold3%7C10_epoch27_val/ParamDenseCropNet_classification_lidc_rfold3%7C10_epoch27_retrieval.npy",
			"experiments/experiments_cl/ParamDenseCropNet_classification_lidc_rfold4%7C10_epoch68_val/ParamDenseCropNet_classification_lidc_rfold4%7C10_epoch68_retrieval.npy",
			"experiments/experiments_cl/ParamDenseCropNet_classification_lidc_rfold5%7C10_epoch497_val/ParamDenseCropNet_classification_lidc_rfold5%7C10_epoch497_retrieval.npy",
			"experiments/experiments_cl/ParamDenseCropNet_classification_lidc_rfold6%7C10_epoch45_val/ParamDenseCropNet_classification_lidc_rfold6%7C10_epoch45_retrieval.npy",
			"experiments/experiments_cl/ParamDenseCropNet_classification_lidc_rfold7%7C10_epoch345_val/ParamDenseCropNet_classification_lidc_rfold7%7C10_epoch345_retrieval.npy",
			"experiments/experiments_cl/ParamDenseCropNet_classification_lidc_rfold8%7C10_epoch47_val/ParamDenseCropNet_classification_lidc_rfold8%7C10_epoch47_retrieval.npy",
			"experiments/experiments_cl/ParamDenseCropNet_classification_lidc_rfold9%7C10_epoch48_val/ParamDenseCropNet_classification_lidc_rfold9%7C10_epoch48_retrieval.npy",
			"experiments/experiments_cl/ParamDenseCropNet_classification_lidc_rfold10%7C10_epoch415_val/ParamDenseCropNet_classification_lidc_rfold10%7C10_epoch415_retrieval.npy"]
evals_dfcnsphr = ["experiments/experiments_cl/ParamDenseCropNet_classification_sph_rfold1%7C10_epoch235_val/ParamDenseCropNet_classification_sph_rfold1%7C10_epoch235_retrieval.npy",
		  "experiments/experiments_cl/ParamDenseCropNet_classification_sph_rfold2%7C10_epoch414_val/ParamDenseCropNet_classification_sph_rfold2%7C10_epoch414_retrieval.npy",
		  "experiments/experiments_cl/ParamDenseCropNet_classification_sph_rfold3%7C10_epoch67_val/ParamDenseCropNet_classification_sph_rfold3%7C10_epoch67_retrieval.npy",
		  "experiments/experiments_cl/ParamDenseCropNet_classification_sph_rfold4%7C10_epoch173_val/ParamDenseCropNet_classification_sph_rfold4%7C10_epoch173_retrieval.npy",
		  "experiments/experiments_cl/ParamDenseCropNet_classification_sph_rfold5%7C10_epoch31_val/ParamDenseCropNet_classification_sph_rfold5%7C10_epoch31_retrieval.npy",
		  "experiments/experiments_cl/ParamDenseCropNet_classification_sph_rfold6%7C10_epoch114_val/ParamDenseCropNet_classification_sph_rfold6%7C10_epoch114_retrieval.npy",
		  "experiments/experiments_cl/ParamDenseCropNet_classification_sph_rfold7%7C10_epoch29_val/ParamDenseCropNet_classification_sph_rfold7%7C10_epoch29_retrieval.npy",
		  "experiments/experiments_cl/ParamDenseCropNet_classification_sph_rfold8%7C10_epoch289_val/ParamDenseCropNet_classification_sph_rfold8%7C10_epoch289_retrieval.npy",
		  "experiments/experiments_cl/ParamDenseCropNet_classification_sph_rfold9%7C10_epoch189_val/ParamDenseCropNet_classification_sph_rfold9%7C10_epoch189_retrieval.npy",
		  "experiments/experiments_cl/ParamDenseCropNet_classification_sph_rfold10%7C10_epoch13_val/ParamDenseCropNet_classification_sph_rfold10%7C10_epoch13_retrieval.npy"]
evals_ensembleprelidcr = ["experiments/experiments_cl/EnsembleNet_lidc_classification_pretrained_3_rfold1%7C10_epoch14_val/EnsembleNet_lidc_classification_pretrained_3_rfold1%7C10_epoch14_retrieval_slicesum.npy",
		       "experiments/experiments_cl/EnsembleNet_lidc_classification_pretrained_3_rfold2%7C10_epoch6_val/EnsembleNet_lidc_classification_pretrained_3_rfold2%7C10_epoch6_retrieval_slicesum.npy",
		       "experiments/experiments_cl/EnsembleNet_lidc_classification_pretrained_3_rfold3%7C10_epoch17_val/EnsembleNet_lidc_classification_pretrained_3_rfold3%7C10_epoch17_retrieval_slicesum.npy",
		       "experiments/experiments_cl/EnsembleNet_lidc_classification_pretrained_3_rfold4%7C10_epoch18_val/EnsembleNet_lidc_classification_pretrained_3_rfold4%7C10_epoch18_retrieval_slicesum.npy",
		       "experiments/experiments_cl/EnsembleNet_lidc_classification_pretrained_3_rfold5%7C10_epoch46_val/EnsembleNet_lidc_classification_pretrained_3_rfold5%7C10_epoch46_retrieval_slicesum.npy",
		       "experiments/experiments_cl/EnsembleNet_lidc_classification_pretrained_3_rfold6%7C10_epoch14_val/EnsembleNet_lidc_classification_pretrained_3_rfold6%7C10_epoch14_retrieval_slicesum.npy",
		       "experiments/experiments_cl/EnsembleNet_lidc_classification_pretrained_3_rfold7%7C10_epoch6_val/EnsembleNet_lidc_classification_pretrained_3_rfold7%7C10_epoch6_retrieval_slicesum.npy",
		       "experiments/experiments_cl/EnsembleNet_lidc_classification_pretrained_3_rfold8%7C10_epoch40_val/EnsembleNet_lidc_classification_pretrained_3_rfold8%7C10_epoch40_retrieval_slicesum.npy",
		       "experiments/experiments_cl/EnsembleNet_lidc_classification_pretrained_3_rfold9%7C10_epoch19_val/EnsembleNet_lidc_classification_pretrained_3_rfold9%7C10_epoch19_retrieval_slicesum.npy",
		       "experiments/experiments_cl/EnsembleNet_lidc_classification_pretrained_3_rfold10%7C10_epoch4_val/EnsembleNet_lidc_classification_pretrained_3_rfold10%7C10_epoch4_retrieval_slicesum.npy"]
evals_ensemblepreadamlidcr = ["experiments/experiments_cl/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold1%7C10_epoch5_val/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold1%7C10_epoch5_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold2%7C10_epoch12_val/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold2%7C10_epoch12_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold3%7C10_epoch34_val/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold3%7C10_epoch34_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold4%7C10_epoch24_val/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold4%7C10_epoch24_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold5%7C10_epoch33_val/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold5%7C10_epoch33_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold6%7C10_epoch25_val/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold6%7C10_epoch25_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold7%7C10_epoch1_val/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold7%7C10_epoch1_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold8%7C10_epoch48_val/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold8%7C10_epoch48_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold9%7C10_epoch37_val/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold9%7C10_epoch37_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold10%7C10_epoch40_val/EnsembleNet_Paramwise_lidc_classification_pretrained_adam_rfold10%7C10_epoch40_retrieval_slicesum.npy"]
evals_ensembleadamsphr = ["experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_adam_rfold1%7C10_epoch6_val/EnsembleNet_Paramwise_sph_classification_adam_rfold1%7C10_epoch6_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_adam_rfold2%7C10_epoch33_val/EnsembleNet_Paramwise_sph_classification_adam_rfold2%7C10_epoch33_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_adam_rfold3%7C10_epoch29_val/EnsembleNet_Paramwise_sph_classification_adam_rfold3%7C10_epoch29_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_adam_rfold4%7C10_epoch6_val/EnsembleNet_Paramwise_sph_classification_adam_rfold4%7C10_epoch6_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_adam_rfold5%7C10_epoch19_val/EnsembleNet_Paramwise_sph_classification_adam_rfold5%7C10_epoch19_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_adam_rfold6%7C10_epoch6_val/EnsembleNet_Paramwise_sph_classification_adam_rfold6%7C10_epoch6_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_adam_rfold7%7C10_epoch20_val/EnsembleNet_Paramwise_sph_classification_adam_rfold7%7C10_epoch20_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_adam_rfold8%7C10_epoch22_val/EnsembleNet_Paramwise_sph_classification_adam_rfold8%7C10_epoch22_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_adam_rfold9%7C10_epoch8_val/EnsembleNet_Paramwise_sph_classification_adam_rfold9%7C10_epoch8_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_adam_rfold10%7C10_epoch18_val/EnsembleNet_Paramwise_sph_classification_adam_rfold10%7C10_epoch18_retrieval_slicesum.npy"]
evals_ensemblepreadamsphr = ["experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold1%7C10_epoch47_val/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold1%7C10_epoch47_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold2%7C10_epoch8_val/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold2%7C10_epoch8_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold3%7C10_epoch11_val/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold3%7C10_epoch11_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold4%7C10_epoch15_val/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold4%7C10_epoch15_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold5%7C10_epoch19_val/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold5%7C10_epoch19_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold6%7C10_epoch39_val/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold6%7C10_epoch39_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold7%7C10_epoch2_val/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold7%7C10_epoch2_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold8%7C10_epoch6_val/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold8%7C10_epoch6_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold9%7C10_epoch5_val/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold9%7C10_epoch5_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold10%7C10_epoch40_val/EnsembleNet_Paramwise_sph_classification_pretrained_adam_rfold10%7C10_epoch40_retrieval_slicesum.npy"]
evals_ensembletransadamsphr = ["experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold1%7C10_epoch31_val/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold1%7C10_epoch31_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold2%7C10_epoch29_val/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold2%7C10_epoch29_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold3%7C10_epoch11_val/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold3%7C10_epoch11_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold4%7C10_epoch7_val/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold4%7C10_epoch7_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold5%7C10_epoch14_val/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold5%7C10_epoch14_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold6%7C10_epoch9_val/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold6%7C10_epoch9_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold7%7C10_epoch33_val/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold7%7C10_epoch33_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold8%7C10_epoch18_val/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold8%7C10_epoch18_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold9%7C10_epoch21_val/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold9%7C10_epoch21_retrieval_slicesum.npy",
			"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold10%7C10_epoch16_val/EnsembleNet_Paramwise_sph_classification_transfer_adam_rfold10%7C10_epoch16_retrieval_slicesum.npy"]
evals_ensemblepretransadamsphr = ["experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold1%7C10_epoch38_val/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold1%7C10_epoch38_retrieval_slicesum.npy",
				"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold2%7C10_epoch2_val/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold2%7C10_epoch2_retrieval_slicesum.npy",
				"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold3%7C10_epoch13_val/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold3%7C10_epoch13_retrieval_slicesum.npy",
				"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold4%7C10_epoch10_val/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold4%7C10_epoch10_retrieval_slicesum.npy",
				"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold5%7C10_epoch3_val/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold5%7C10_epoch3_retrieval_slicesum.npy",
				"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold6%7C10_epoch19_val/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold6%7C10_epoch19_retrieval_slicesum.npy",
				"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold7%7C10_epoch3_val/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold7%7C10_epoch3_retrieval_slicesum.npy",
				"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold8%7C10_epoch7_val/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold8%7C10_epoch7_retrieval_slicesum.npy",
				"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold9%7C10_epoch3_val/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold9%7C10_epoch3_retrieval_slicesum.npy",
				"experiments/experiments_cl/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold10%7C10_epoch4_val/EnsembleNet_Paramwise_sph_classification_pretrained_transfer_adam_rfold10%7C10_epoch4_retrieval_slicesum.npy"]
evals_rmtn1sphr = ["experiments/experiments_cl/RegularlySharedNet_classification_bsph_2_rfold1_epoch1062_train/RegularlySharedNet_classification_bsph_2_rfold1_epoch1062_retrieval2.npy",
		       "experiments/experiments_cl/RegularlySharedNet_classification_bsph_rfold2_epoch1152_train/RegularlySharedNet_classification_bsph_rfold2_epoch1152_retrieval2.npy",
		       "experiments/experiments_cl/RegularlySharedNet_classification_bsph_rfold3_epoch418_train/RegularlySharedNet_classification_bsph_rfold3_epoch418_retrieval2.npy",
		       "experiments/experiments_cl/RegularlySharedNet_classification_bsph_rfold4_epoch750_train/RegularlySharedNet_classification_bsph_rfold4_epoch750_retrieval2.npy",
		       "experiments/experiments_cl/RegularlySharedNet_classification_bsph_rfold5_epoch818_train/RegularlySharedNet_classification_bsph_rfold5_epoch818_retrieval2.npy"]
evals_rmtn1sph = ["experiments/experiments_cl/RegularlySharedNet_classification_4_fold1_epoch1000_val/RegularlySharedNet_classification_4_fold1_epoch1000_retrieval2.npy",
		  "experiments/experiments_cl/RegularlySharedNet_classification_4_fold2_epoch246_val/RegularlySharedNet_classification_4_fold2_epoch246_retrieval2.npy",
		  "experiments/experiments_cl/RegularlySharedNet_classification_4_fold3_epoch982_val/RegularlySharedNet_classification_4_fold3_epoch982_retrieval2.npy",
		  "experiments/experiments_cl/RegularlySharedNet_classification_4_fold4_epoch779_val/RegularlySharedNet_classification_4_fold4_epoch779_retrieval2.npy",
		  "experiments/experiments_cl/RegularlySharedNet_classification_4_fold5_epoch809_val/RegularlySharedNet_classification_4_fold5_epoch809_retrieval2.npy"]
evals_rmtn2lidc = ["experiments/experiments_cl/RegularlySharedNet_classification_3_fold1_stage2_epoch217_val/RegularlySharedNet_classification_3_fold1_stage2_epoch217_retrieval.npy",
		  "experiments/experiments_cl/RegularlySharedNet_classification_3_fold2_epoch840_val/RegularlySharedNet_classification_3_fold2_epoch840_retrieval.npy",
		  "experiments/experiments_cl/RegularlySharedNet_classification_3_fold3_epoch983_val/RegularlySharedNet_classification_3_fold3_epoch983_retrieval.npy",
		  "experiments/experiments_cl/RegularlySharedNet_classification_3_fold4_epoch652_val/RegularlySharedNet_classification_3_fold4_epoch652_retrieval.npy",
		  "experiments/experiments_cl/RegularlySharedNet_classification_3_fold5_epoch283_val/RegularlySharedNet_classification_3_fold5_epoch283_retrieval.npy"]
evals_bmtnlidcr = ["experiments/experiments_cl/BaseweightSharedNet_classification_rfold1_epoch1027_val/BaseweightSharedNet_classification_rfold1_epoch1027_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold2_epoch521_val/BaseweightSharedNet_classification_rfold2_epoch521_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold3_epoch658_val/BaseweightSharedNet_classification_rfold3_epoch658_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold4_epoch1024_val/BaseweightSharedNet_classification_rfold4_epoch1024_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold5_epoch845_val/BaseweightSharedNet_classification_rfold5_epoch845_retrieval.npy"]
evals_bmtnsphr = ["experiments/experiments_cl/BaseweightSharedNet_classification_rfold1_epoch747_val/BaseweightSharedNet_classification_rfold1_epoch747_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold2_epoch617_val/BaseweightSharedNet_classification_rfold2_epoch617_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold3_epoch627_val/BaseweightSharedNet_classification_rfold3_epoch627_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold4_epoch552_val/BaseweightSharedNet_classification_rfold4_epoch552_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold5_epoch740_val/BaseweightSharedNet_classification_rfold5_epoch740_retrieval2.npy"]
evals_bmtn2lidcr = ["experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold1_stage2_epoch176_val/BaseweightSharedNet_classification_2_rfold1_stage2_epoch176_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold2_epoch890_val/BaseweightSharedNet_classification_2_rfold2_epoch890_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold3_epoch428_val/BaseweightSharedNet_classification_2_rfold3_epoch428_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold4_epoch1220_val/BaseweightSharedNet_classification_2_rfold4_epoch1220_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold5_epoch530_val/BaseweightSharedNet_classification_2_rfold5_epoch530_retrieval.npy"]
evals_bmtn2sphr = ["experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold1_epoch420_val/BaseweightSharedNet_classification_2_rfold1_epoch420_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold2_epoch260_val/BaseweightSharedNet_classification_2_rfold2_epoch260_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold3_epoch428_val/BaseweightSharedNet_classification_2_rfold3_epoch428_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold4_epoch810_val/BaseweightSharedNet_classification_2_rfold4_epoch810_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold5_epoch230_val/BaseweightSharedNet_classification_2_rfold5_epoch230_retrieval2.npy"]
evals_bmtn3lidcr = ["experiments/experiments_cl/BaseweightSharedNet_classification_3_rfold1_epoch1200_val/BaseweightSharedNet_classification_3_rfold1_epoch1200_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_3_rfold2_epoch1360_val/BaseweightSharedNet_classification_3_rfold2_epoch1360_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_3_rfold3_epoch1360_val/BaseweightSharedNet_classification_3_rfold3_epoch1360_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_3_rfold4_epoch1430_val/BaseweightSharedNet_classification_3_rfold4_epoch1430_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_3_rfold5_epoch970_val/BaseweightSharedNet_classification_3_rfold5_epoch970_retrieval.npy"]
evals_bmtn3sphr = ["experiments/experiments_cl/BaseweightSharedNet_classification_3_rfold1_epoch630_val/BaseweightSharedNet_classification_3_rfold1_epoch630_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_3_rfold2_epoch580_val/BaseweightSharedNet_classification_3_rfold2_epoch580_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_3_rfold3_epoch200_val/BaseweightSharedNet_classification_3_rfold3_epoch200_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_3_rfold4_epoch630_val/BaseweightSharedNet_classification_3_rfold4_epoch630_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_3_rfold5_epoch1450_val/BaseweightSharedNet_classification_3_rfold5_epoch1450_retrieval2.npy"]
evals_bmtn4lidcr = ["experiments/experiments_cl/BaseweightSharedNet_classification_4_rfold1_epoch1230_val/BaseweightSharedNet_classification_4_rfold1_epoch1230_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_4_rfold2_epoch710_val/BaseweightSharedNet_classification_4_rfold2_epoch710_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_4_rfold3_epoch900_val/BaseweightSharedNet_classification_4_rfold3_epoch900_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_4_rfold4_epoch880_val/BaseweightSharedNet_classification_4_rfold4_epoch880_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_4_rfold5_epoch640_val/BaseweightSharedNet_classification_4_rfold5_epoch640_retrieval.npy"]
evals_bmtn4sphr = ["experiments/experiments_cl/BaseweightSharedNet_classification_4_rfold1_epoch250_val/BaseweightSharedNet_classification_4_rfold1_epoch250_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_4_rfold2_epoch470_val/BaseweightSharedNet_classification_4_rfold2_epoch470_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_4_rfold3_epoch290_val/BaseweightSharedNet_classification_4_rfold3_epoch290_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_4_rfold4_epoch90_val/BaseweightSharedNet_classification_4_rfold4_epoch90_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_4_rfold5_epoch150_val/BaseweightSharedNet_classification_4_rfold5_epoch150_retrieval2.npy"]
evals_bmtnb4lidcr = ["experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold1_epoch1467_val/BaseweightSharedNet_classification_b4_rfold1_epoch1467_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold2_epoch1118_val/BaseweightSharedNet_classification_b4_rfold2_epoch1118_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold3_epoch1124_val/BaseweightSharedNet_classification_b4_rfold3_epoch1124_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold4_epoch1180_val/BaseweightSharedNet_classification_b4_rfold4_epoch1180_retrieval.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold5_epoch1473_val/BaseweightSharedNet_classification_b4_rfold5_epoch1473_retrieval.npy"]
evals_bmtnb4sphr = ["experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold1_epoch1467_val/BaseweightSharedNet_classification_b4_rfold1_epoch1467_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold2_epoch1118_val/BaseweightSharedNet_classification_b4_rfold2_epoch1118_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold3_epoch1362_val/BaseweightSharedNet_classification_b4_rfold3_epoch1362_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold4_epoch116_val/BaseweightSharedNet_classification_b4_rfold4_epoch116_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold5_epoch654_val/BaseweightSharedNet_classification_b4_rfold5_epoch654_retrieval2.npy"]
evals_bmtnb4sphr_2 = ["experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold1_epoch1467_val/BaseweightSharedNet_classification_b4_rfold1_epoch1467_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold2_epoch1099_val/BaseweightSharedNet_classification_b4_rfold2_epoch1099_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold3_epoch1478_val/BaseweightSharedNet_classification_b4_rfold3_epoch1478_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold4_epoch93_val/BaseweightSharedNet_classification_b4_rfold4_epoch93_retrieval2.npy",
	       "experiments/experiments_cl/BaseweightSharedNet_classification_b4_rfold5_epoch662_val/BaseweightSharedNet_classification_b4_rfold5_epoch662_retrieval2.npy"]
evals_bmtnlidcrcv10 = ["experiments/experiments_cl/BaseweightSharedNet_classification_rfold1%7C10_epoch1264_val/BaseweightSharedNet_classification_rfold1%7C10_epoch1264_retrieval.npy",
		       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold2%7C10_epoch178_val/BaseweightSharedNet_classification_rfold2%7C10_epoch178_retrieval.npy",
		       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold3%7C10_epoch552_val/BaseweightSharedNet_classification_rfold3%7C10_epoch552_retrieval.npy",
		       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold4%7C10_epoch487_val/BaseweightSharedNet_classification_rfold4%7C10_epoch487_retrieval.npy",
		       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold5%7C10_epoch717_val/BaseweightSharedNet_classification_rfold5%7C10_epoch717_retrieval.npy",
		       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold6%7C10_epoch445_val/BaseweightSharedNet_classification_rfold6%7C10_epoch445_retrieval.npy",
		       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold7%7C10_epoch429_val/BaseweightSharedNet_classification_rfold7%7C10_epoch429_retrieval.npy",
		       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold8%7C10_epoch160_val/BaseweightSharedNet_classification_rfold8%7C10_epoch160_retrieval.npy",
		       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold9%7C10_epoch238_val/BaseweightSharedNet_classification_rfold9%7C10_epoch238_retrieval.npy",
		       "experiments/experiments_cl/BaseweightSharedNet_classification_rfold10%7C10_epoch1139_val/BaseweightSharedNet_classification_rfold10%7C10_epoch1139_retrieval.npy"]
evals_bmtnsphrcv10 = ["experiments/experiments_cl/BaseweightSharedNet_classification_rfold1%7C10_epoch558_val/BaseweightSharedNet_classification_rfold1%7C10_epoch558_retrieval2.npy",
		      "experiments/experiments_cl/BaseweightSharedNet_classification_rfold2%7C10_epoch202_val/BaseweightSharedNet_classification_rfold2%7C10_epoch202_retrieval2.npy",
		      "experiments/experiments_cl/BaseweightSharedNet_classification_rfold3%7C10_epoch538_val/BaseweightSharedNet_classification_rfold3%7C10_epoch538_retrieval2.npy",
		      "experiments/experiments_cl/BaseweightSharedNet_classification_rfold4%7C10_epoch271_val/BaseweightSharedNet_classification_rfold4%7C10_epoch271_retrieval2.npy",
		      "experiments/experiments_cl/BaseweightSharedNet_classification_rfold5%7C10_epoch640_val/BaseweightSharedNet_classification_rfold5%7C10_epoch640_retrieval2.npy",
		      "experiments/experiments_cl/BaseweightSharedNet_classification_rfold6%7C10_epoch197_val/BaseweightSharedNet_classification_rfold6%7C10_epoch197_retrieval.npy",
		      "experiments/experiments_cl/BaseweightSharedNet_classification_rfold7%7C10_epoch84_val/BaseweightSharedNet_classification_rfold7%7C10_epoch84_retrieval.npy",
		      "experiments/experiments_cl/BaseweightSharedNet_classification_rfold8%7C10_epoch112_val/BaseweightSharedNet_classification_rfold8%7C10_epoch112_retrieval.npy",
		      "experiments/experiments_cl/BaseweightSharedNet_classification_rfold9%7C10_epoch238_val/BaseweightSharedNet_classification_rfold9%7C10_epoch238_retrieval.npy",
		      "experiments/experiments_cl/BaseweightSharedNet_classification_rfold10%7C10_epoch234_val/BaseweightSharedNet_classification_rfold10%7C10_epoch234_retrieval.npy"]
evals_bmtn2lidcrcv10 = ["experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold1%7C10_epoch130_val/BaseweightSharedNet_classification_2_rfold1%7C10_epoch130_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold2%7C10_epoch780_val/BaseweightSharedNet_classification_2_rfold2%7C10_epoch780_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold3%7C10_epoch120_val/BaseweightSharedNet_classification_2_rfold3%7C10_epoch120_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold4%7C10_epoch1060_val/BaseweightSharedNet_classification_2_rfold4%7C10_epoch1060_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold5%7C10_epoch450_val/BaseweightSharedNet_classification_2_rfold5%7C10_epoch450_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold6%7C10_epoch480_val/BaseweightSharedNet_classification_2_rfold6%7C10_epoch480_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold7%7C10_epoch1340_val/BaseweightSharedNet_classification_2_rfold7%7C10_epoch1340_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold8%7C10_epoch620_val/BaseweightSharedNet_classification_2_rfold8%7C10_epoch620_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold9%7C10_epoch920_val/BaseweightSharedNet_classification_2_rfold9%7C10_epoch920_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_classification_2_rfold10%7C10_epoch1290_val/BaseweightSharedNet_classification_2_rfold10%7C10_epoch1290_retrieval.npy"]
evals_bsdlidcrcv10 = ["experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold1%7C10_epoch119_val/BaseweightSharedNet_densecropnet_classification_adam_rfold1%7C10_epoch119_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold2%7C10_epoch494_val/BaseweightSharedNet_densecropnet_classification_adam_rfold2%7C10_epoch494_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold3%7C10_epoch66_val/BaseweightSharedNet_densecropnet_classification_adam_rfold3%7C10_epoch66_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold4%7C10_epoch446_val/BaseweightSharedNet_densecropnet_classification_adam_rfold4%7C10_epoch446_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold5%7C10_epoch369_val/BaseweightSharedNet_densecropnet_classification_adam_rfold5%7C10_epoch369_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold6%7C10_epoch792_val/BaseweightSharedNet_densecropnet_classification_adam_rfold6%7C10_epoch792_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold7%7C10_epoch520_val/BaseweightSharedNet_densecropnet_classification_adam_rfold7%7C10_epoch520_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold8%7C10_epoch469_val/BaseweightSharedNet_densecropnet_classification_adam_rfold8%7C10_epoch469_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold9%7C10_epoch401_val/BaseweightSharedNet_densecropnet_classification_adam_rfold9%7C10_epoch401_retrieval.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold10%7C10_epoch199_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold10%7C10_epoch199_retrieval.npy"]
evals_bsd2lidcrcv10 = ['experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold1%7C10_epoch101_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold1%7C10_epoch101_retrieval.npy',
			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold10%7C10_epoch199_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold10%7C10_epoch199_retrieval.npy',
			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold2%7C10_epoch900_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold2%7C10_epoch900_retrieval.npy',
			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold3%7C10_epoch570_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold3%7C10_epoch570_retrieval.npy',
			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold4%7C10_epoch351_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold4%7C10_epoch351_retrieval.npy',
			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold5%7C10_epoch101_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold5%7C10_epoch101_retrieval.npy',
			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold6%7C10_epoch493_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold6%7C10_epoch493_retrieval.npy',
			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold7%7C10_epoch419_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold7%7C10_epoch419_retrieval.npy',
			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold8%7C10_epoch176_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold8%7C10_epoch176_retrieval.npy',
			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold9%7C10_epoch978_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold9%7C10_epoch978_retrieval.npy']
evals_bsdsphrcv10 = ["experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold1%7C10_epoch230_val/BaseweightSharedNet_densecropnet_classification_adam_rfold1%7C10_epoch230_retrieval2.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold2%7C10_epoch906_val/BaseweightSharedNet_densecropnet_classification_adam_rfold2%7C10_epoch906_retrieval2.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold3%7C10_epoch732_val/BaseweightSharedNet_densecropnet_classification_adam_rfold3%7C10_epoch732_retrieval2.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold4%7C10_epoch298_val/BaseweightSharedNet_densecropnet_classification_adam_rfold4%7C10_epoch298_retrieval2.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold5%7C10_epoch344_val/BaseweightSharedNet_densecropnet_classification_adam_rfold5%7C10_epoch344_retrieval2.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold6%7C10_epoch506_val/BaseweightSharedNet_densecropnet_classification_adam_rfold6%7C10_epoch506_retrieval2.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold7%7C10_epoch188_val/BaseweightSharedNet_densecropnet_classification_adam_rfold7%7C10_epoch188_retrieval2.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold8%7C10_epoch264_val/BaseweightSharedNet_densecropnet_classification_adam_rfold8%7C10_epoch264_retrieval2.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_rfold9%7C10_epoch746_val/BaseweightSharedNet_densecropnet_classification_adam_rfold9%7C10_epoch746_retrieval2.npy",
			"experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold10%7C10_epoch27_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold10%7C10_epoch27_retrieval2.npy"]
evals_bsd2sphrcv10 = ['experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold1%7C10_epoch341_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold1%7C10_epoch341_retrieval2.npy',
			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold2%7C10_epoch896_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold2%7C10_epoch896_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold3%7C10_epoch180_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold3%7C10_epoch180_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold4%7C10_epoch925_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold4%7C10_epoch925_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold5%7C10_epoch213_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold5%7C10_epoch213_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold6%7C10_epoch317_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold6%7C10_epoch317_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold7%7C10_epoch132_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold7%7C10_epoch132_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold8%7C10_epoch191_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold8%7C10_epoch191_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold9%7C10_epoch710_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold9%7C10_epoch710_retrieval2.npy', 			'experiments/experiments_cl/BaseweightSharedNet_densecropnet_classification_adam_2_rfold10%7C10_epoch27_val/BaseweightSharedNet_densecropnet_classification_adam_2_rfold10%7C10_epoch27_retrieval2.npy']
evals_mtksphrcv10 = ['experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_adam_rfold1%7C10_epoch51_val/BaseweightSharedBNNet_bf_classification_adam_rfold1%7C10_epoch51_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_adam_rfold2%7C10_epoch33_val/BaseweightSharedBNNet_bf_classification_adam_rfold2%7C10_epoch33_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_adam_rfold4%7C10_epoch56_val/BaseweightSharedBNNet_bf_classification_adam_rfold4%7C10_epoch56_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_adam_rfold5%7C10_epoch23_val/BaseweightSharedBNNet_bf_classification_adam_rfold5%7C10_epoch23_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_adam_rfold6%7C10_epoch53_val/BaseweightSharedBNNet_bf_classification_adam_rfold6%7C10_epoch53_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_adam_rfold7%7C10_epoch51_val/BaseweightSharedBNNet_bf_classification_adam_rfold7%7C10_epoch51_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_adam_rfold8%7C10_epoch23_val/BaseweightSharedBNNet_bf_classification_adam_rfold8%7C10_epoch23_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_adam_rfold9%7C10_epoch60_val/BaseweightSharedBNNet_bf_classification_adam_rfold9%7C10_epoch60_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_adam_rfold3%7C10_epoch1_val/BaseweightSharedBNNet_classification_adam_rfold3%7C10_epoch1_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_adam_rfold10%7C10_epoch50_val/BaseweightSharedBNNet_bf_classification_adam_rfold10%7C10_epoch50_retrieval_slicesum2.npy']
evals_mtkoalidcrcv10 = ['experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold1%7C10_epoch3_val_1/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold1%7C10_epoch3_retrieval_slicesum.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold2%7C10_epoch38_val_1/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold2%7C10_epoch38_retrieval_slicesum.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold3%7C10_epoch22_val_1/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold3%7C10_epoch22_retrieval_slicesum.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold4%7C10_epoch25_val_1/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold4%7C10_epoch25_retrieval_slicesum.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold5%7C10_epoch37_val_1/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold5%7C10_epoch37_retrieval_slicesum.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold6%7C10_epoch38_val_1/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold6%7C10_epoch38_retrieval_slicesum.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold7%7C10_epoch19_val_1/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold7%7C10_epoch19_retrieval_slicesum.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold8%7C10_epoch25_val_1/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold8%7C10_epoch25_retrieval_slicesum.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold9%7C10_epoch1_val_1/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold9%7C10_epoch1_retrieval_slicesum.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold10%7C10_epoch3_val_1/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold10%7C10_epoch3_retrieval_slicesum.npy']
evals_mtkoasphrcv10 = ['experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold1%7C10_epoch29_val_2/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold1%7C10_epoch29_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold2%7C10_epoch27_val_2/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold2%7C10_epoch27_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold3%7C10_epoch55_val_2/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold3%7C10_epoch55_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold4%7C10_epoch37_val_2/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold4%7C10_epoch37_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold5%7C10_epoch20_val_2/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold5%7C10_epoch20_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold6%7C10_epoch53_val_2/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold6%7C10_epoch53_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold7%7C10_epoch41_val_2/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold7%7C10_epoch41_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold8%7C10_epoch41_val_2/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold8%7C10_epoch41_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold9%7C10_epoch47_val_2/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold9%7C10_epoch47_retrieval_slicesum2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold10%7C10_epoch19_val_2/BaseweightSharedBNNet_bf_classification_pretrained_oa_adam_rfold10%7C10_epoch19_retrieval_slicesum2.npy']
evals_bsessphrcv10 = ["experiments/experiments_cl/BaseweightSharedBNNet_classification_adam_rfold1%7C10_epoch7_val/BaseweightSharedBNNet_classification_adam_rfold1%7C10_epoch7_retrieval_slicesum2.npy",
					"experiments/experiments_cl/BaseweightSharedBNNet_classification_adam_rfold2%7C10_epoch23_val/BaseweightSharedBNNet_classification_adam_rfold2%7C10_epoch23_retrieval_slicesum2.npy",
					"experiments/experiments_cl/BaseweightSharedBNNet_classification_adam_rfold3%7C10_epoch1_val/BaseweightSharedBNNet_classification_adam_rfold3%7C10_epoch1_retrieval_slicesum2.npy",
					"experiments/experiments_cl/BaseweightSharedBNNet_classification_adam_rfold4%7C10_epoch19_val/BaseweightSharedBNNet_classification_adam_rfold4%7C10_epoch19_retrieval_slicesum2.npy",
					"experiments/experiments_cl/BaseweightSharedBNNet_classification_adam_rfold5%7C10_epoch37_val/BaseweightSharedBNNet_classification_adam_rfold5%7C10_epoch37_retrieval_slicesum2.npy",
					"experiments/experiments_cl/BaseweightSharedBNNet_classification_adam_rfold6%7C10_epoch4_val/BaseweightSharedBNNet_classification_adam_rfold6%7C10_epoch4_retrieval_slicesum2.npy",
					"experiments/experiments_cl/BaseweightSharedBNNet_classification_adam_2_rfold7%7C10_epoch3_val/BaseweightSharedBNNet_classification_adam_2_rfold7%7C10_epoch3_retrieval_slicesum2.npy",
					"experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_adam_2_rfold8%7C10_epoch11_val/BaseweightSharedBNNet_classification_pretrained_adam_2_rfold8%7C10_epoch11_retrieval_slicesum2.npy",
					"experiments/experiments_cl/BaseweightSharedBNNet_classification_adam_rfold9%7C10_epoch4_val/BaseweightSharedBNNet_classification_adam_rfold9%7C10_epoch4_retrieval_slicesum2.npy",
					"experiments/experiments_cl/BaseweightSharedBNNet_classification_adam_rfold10%7C10_stage2_epoch1_val/BaseweightSharedBNNet_classification_adam_rfold10%7C10_stage2_epoch1_retrieval_slicesum2.npy"]
evals_bsesoalidcrcv10 = ['experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold1%7C10_stage2_epoch34_val_1/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold1%7C10_stage2_epoch34_retrieval.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold2%7C10_epoch3_val_1/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold2%7C10_epoch3_retrieval.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold3%7C10_epoch1_val_1/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold3%7C10_epoch1_retrieval.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold4%7C10_epoch53_val_1/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold4%7C10_epoch53_retrieval.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold5%7C10_epoch5_val_1/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold5%7C10_epoch5_retrieval.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold6%7C10_epoch40_val_1/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold6%7C10_epoch40_retrieval.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold7%7C10_epoch19_val_1/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold7%7C10_epoch19_retrieval.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold8%7C10_epoch3_val_1/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold8%7C10_epoch3_retrieval.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold9%7C10_epoch41_val_1/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold9%7C10_epoch41_retrieval.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold10%7C10_epoch24_val_1/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold10%7C10_epoch24_retrieval.npy']
evals_bsesoasphrcv10 = ['experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold1%7C10_stage2_epoch29_val/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold1%7C10_stage2_epoch29_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold2%7C10_epoch51_val_2/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold2%7C10_epoch51_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold3%7C10_epoch42_val_2/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold3%7C10_epoch42_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold4%7C10_epoch5_val_2/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold4%7C10_epoch5_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold5%7C10_epoch48_val_2/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold5%7C10_epoch48_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold6%7C10_epoch59_val_2/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold6%7C10_epoch59_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold7%7C10_epoch49_val_2/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold7%7C10_epoch49_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold8%7C10_epoch46_val_2/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold8%7C10_epoch46_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold9%7C10_epoch47_val_2/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold9%7C10_epoch47_retrieval2.npy', 'experiments/experiments_cl/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold10%7C10_epoch33_val_2/BaseweightSharedBNNet_classification_pretrained_oa_adam_rfold10%7C10_epoch33_retrieval2.npy']

evals_densenet = ["experiments/experiments_cl/DenseNet_Iterative_trand_fold1_epoch21_val/DenseNet_Iterative_trand_fold1_epoch21_retrieval.npy",
	"experiments/experiments_cl/DenseNet_Iterative_trand_fold2_epoch81_val/DenseNet_Iterative_trand_fold2_epoch81_retrieval.npy",
	"experiments/experiments_cl/DenseNet_Iterative_trand_fold3_epoch111_val/DenseNet_Iterative_trand_fold3_epoch111_retrieval.npy",
	"experiments/experiments_cl/DenseNet_Iterative_trand_fold4_epoch39_val/DenseNet_Iterative_trand_fold4_epoch39_retrieval.npy",
	"experiments/experiments_cl/DenseNet_Iterative_trand_fold5_epoch84_val/DenseNet_Iterative_trand_fold5_epoch84_retrieval.npy"]
evals_densecropnet = ["experiments/experiments_cl/DensecropNet_2_trand_fold1_epoch13_val/DensecropNet_2_trand_fold1_epoch13_retrieval.npy",
	 "experiments/experiments_cl/DensecropNet_Iterative_2_trand_fold2_epoch126_val/DensecropNet_Iterative_2_trand_fold2_epoch126_retrieval.npy",
	 "experiments/experiments_cl/DensecropNet_Iterative_2_trand_fold3_epoch18_val/DensecropNet_Iterative_2_trand_fold3_epoch18_retrieval.npy",
	 "experiments/experiments_cl/DensecropNet_Iterative_2_trand_fold4_epoch15_val/DensecropNet_Iterative_2_trand_fold4_epoch15_retrieval.npy",
	 "experiments/experiments_cl/DensecropNet_Iterative_2_trand_fold5_epoch6_val/DensecropNet_Iterative_2_trand_fold5_epoch6_retrieval.npy"]
evals_multicropnet = ["experiments/experiments_cl/MulticropNet_trand_fold1_epoch14_val/MulticropNet_trand_fold1_epoch14_retrieval.npy",
	 "experiments/experiments_cl/MulticropNet_trand_fold2_epoch31_val/MulticropNet_trand_fold2_epoch31_retrieval.npy",
	 "experiments/experiments_cl/MulticropNet_trand_fold3_epoch8_val/MulticropNet_trand_fold3_epoch8_retrieval.npy",
	 "experiments/experiments_cl/MulticropNet_trand_fold4_epoch32_val/MulticropNet_trand_fold4_epoch32_retrieval.npy",
	 "experiments/experiments_cl/MulticropNet_trand_fold5_epoch15_val/MulticropNet_trand_fold5_epoch15_retrieval.npy"]
evals_ipris = ["experiments/experiments_cl/ipris_fold1_svm_retrieval.npy",
	 "experiments/experiments_cl/ipris_fold2_svm_retrieval.npy",
	 "experiments/experiments_cl/ipris_fold3_svm_retrieval.npy",
	 "experiments/experiments_cl/ipris_fold4_svm_retrieval.npy",
	 "experiments/experiments_cl/ipris_fold5_svm_retrieval.npy"]

evals_densecropnet_rg = ["experiments/experiments_cl/DensecropNet_regression_2_fold1_epoch33_val/DensecropNet_regression_2_fold1_epoch33_regressionretrieval.npy",
			 "experiments/experiments_cl/DensecropNet_regression_2_fold2_epoch87_val/DensecropNet_regression_2_fold2_epoch87_regressionretrieval.npy",
			 "experiments/experiments_cl/DensecropNet_regression_2_fold3_epoch303_val/DensecropNet_regression_2_fold3_epoch303_regressionretrieval.npy",
			 "experiments/experiments_cl/DensecropNet_regression_2_fold4_epoch60_val/DensecropNet_regression_2_fold4_epoch60_regressionretrieval.npy",
			 "experiments/experiments_cl/DensecropNet_regression_2_fold5_epoch90_val/DensecropNet_regression_2_fold5_epoch90_regressionretrieval.npy"]

storename = "experiments/experiments_cl/BaseweightSharedBNNet_sph_classification_scratch_oa_adam_roc.npy"
#evals = evals_mtkoalidcrcv10
evals = glob.glob('experiments/experiments_cl/cross_validation/*/*_retrieval2.npy')
evals.append(evals.pop(1))
print(evals)
evaluations = []
evadicts = {'sensitivity': [], 'specificity': [], 'auc': [], 'accuracy': []}
for e in range(len(evals)):
	evaluation = np.load(evals[e])
	print("fold:%d" %(e+1))
	evadict = eva.binclass_evaluation(evaluation[1], evaluation[0], False, True)
	for edkey in evadict.keys():
		evadicts[edkey].append(evadict[edkey])
	evaluations.append(evaluation)
evaluations = np.concatenate(evaluations, axis=1)
print("overall:")
eva.binclass_evaluation(evaluations[1], evaluations[0], False, True, storename)
for edkey in evadicts.keys():
	print('%s: mean %f dev %f' %(edkey, np.array(evadicts[edkey]).mean(), np.array(evadicts[edkey]).std()))
#eva.regression_evaluation(evaluations[1], evaluations[0])